# Generated by Django 3.2.13 on 2022-06-05 09:55

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20211015_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='announce_at',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
    ]
