# Generated by Django 3.2.13 on 2022-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20220605_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvote_badge',
            field=models.BooleanField(default=False),
        ),
    ]
