# Generated by Django 3.2.13 on 2022-11-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20220918_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seoTitle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seoDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seoKeywords',
            field=models.TextField(null=True),
        ),
    ]
