# Generated by Django 3.2.13 on 2022-12-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20221213_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='message_id_to_buddy_from_bot',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='message_id_to_buddy_from_bot',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
