# Generated by Django 3.2.13 on 2022-12-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20221215_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='message_id_to_buddy_from_bot',
        ),
    ]
