# Generated by Django 3.2.13 on 2022-12-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_remove_historicalpost_message_id_to_buddy_from_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message_id_to_buddy_from_bot',
            new_name='message_id_to_buddy_group_from_bot',
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='message_id_to_buddy_group_from_bot',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='message_id_to_responsible_buddy_user_from_bot',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
