# Generated by Django 3.2.13 on 2022-12-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20221216_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='message_id_to_buddy_group_from_bot',
        ),
    ]
