# Generated by Django 3.2.13 on 2022-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_remove_historicalpost_message_id_to_buddy_group_from_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
