# Generated by Django 3.2.13 on 2022-12-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20221219_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='task_done',
        ),
    ]
