# Generated by Django 3.2.13 on 2022-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_remove_historicalpost_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_task_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
