# Generated by Django 3.2.13 on 2023-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_post_time_task_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_slug', models.CharField(db_column='post_slug', max_length=128, null=True)),
                ('foo_name', models.CharField(db_column='foo_name', max_length=128, null=True)),
            ],
            options={
                'db_table': 'post_exceptions',
            },
        ),
    ]
