# Generated by Django 3.2.13 on 2022-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_postexceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
