# Generated by Django 3.2.13 on 2023-06-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_post_time_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='seo_description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='seo_title',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
