# Generated by Django 3.2.13 on 2023-05-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
