# Generated by Django 3.2.13 on 2022-07-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_membership_platform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_id',
            field=models.UUIDField(),
        ),
    ]
