# Generated by Django 3.2.13 on 2023-02-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20221128_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUserChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_yesterday_best_posts', models.BooleanField(default=False)),
                ('tg_weekly_best_posts', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user_choises', to='users.user')),
            ],
            options={
                'db_table': 'subscription_user_choises',
            },
        ),
    ]
