# Generated by Django 3.2.13 on 2023-02-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_subscriptionuserchoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionuserchoise',
            name='tg_weekly_best_posts',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Лучшие посты и интересные интро за прошедшую неделю'),
        ),
        migrations.AlterField(
            model_name='subscriptionuserchoise',
            name='tg_yesterday_best_posts',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Лучшие посты и самые интересные интро за вчерашний день'),
        ),
    ]
