# Generated by Django 3.2.13 on 2023-02-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20230210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionuserchoise',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_user_choises', to='users.user'),
        ),
    ]
