# Generated by Django 3.2.13 on 2023-02-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_subscriptionuserchoise_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionuserchoise',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscriptionuserchoise',
            name='daily_email_digest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Ежедневная e-mail рассылка'),
        ),
        migrations.AddField(
            model_name='subscriptionuserchoise',
            name='weekly_email_digest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Еженедельная e-mail рассылка'),
        ),
    ]
