# Generated by Django 3.2.13 on 2023-02-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_subscriptionuserchoise_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionUserChoise',
        ),
    ]
