# Generated by Django 3.2.13 on 2023-02-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_subscriptionuserchoise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_coffee_is',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], db_column='random_coffee_is', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='random_coffee_tg_link',
            field=models.CharField(db_column='random_coffee_tg_link', max_length=128, null=True),
        ),
    ]
