# Generated by Django 3.2.13 on 2023-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_subscriptionuserchoise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_email_digest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Ежедневная e-mail рассылка'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_weekly_best_posts',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Лучшие посты и интересные интро за прошедшую неделю'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_yesterday_best_posts',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Лучшие посты и самые интересные интро за вчерашний день'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_email_digest',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True, verbose_name='Еженедельная e-mail рассылка'),
        ),
    ]
