# Generated by Django 3.2.13 on 2023-02-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20230218_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_coffee_today',
            field=models.BooleanField(db_column='random_coffee_today', default=True),
        ),
    ]
