# Generated by Django 3.2.13 on 2023-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_random_coffee_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_coffee_was_already',
            field=models.TextField(db_column='random_coffee_was_already', null=True),
        ),
    ]
