# Generated by Django 3.2.13 on 2023-02-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_random_coffee_was_already'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_was_already',
        ),
        migrations.AddField(
            model_name='user',
            name='random_coffee_past_partners',
            field=models.TextField(db_column='random_coffee_past_partners', null=True),
        ),
    ]
