# Generated by Django 3.2.13 on 2023-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20230223_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_email_digest',
            field=models.BooleanField(default=False, verbose_name='Ежедневная e-mail рассылка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_weekly_best_posts',
            field=models.BooleanField(default=False, verbose_name='Лучшие посты и интересные интро за прошедшую неделю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_yesterday_best_posts',
            field=models.BooleanField(default=False, verbose_name='Лучшие посты и самые интересные интро за вчерашний день'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_email_digest',
            field=models.BooleanField(default=False, verbose_name='Еженедельная e-mail рассылка'),
        ),
    ]
