# Generated by Django 3.2.13 on 2023-02-18 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_random_coffee_current_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_current_partner',
        ),
        migrations.AddField(
            model_name='user',
            name='random_coffee_current_partner_id',
            field=models.UUIDField(db_column='random_coffee_current_partner_id', default=uuid.uuid4, null=True),
        ),
    ]
