# Generated by Django 3.2.13 on 2023-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20230223_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_weekly_best_posts',
            field=models.BooleanField(default=False, verbose_name='Лучшие посты и интересные интро клуба за прошедшую неделю в Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_yesterday_best_posts',
            field=models.BooleanField(default=False, verbose_name='Лучшие посты и самые интересные интро клуба за вчерашний день в Telegram'),
        ),
        migrations.DeleteModel(
            name='SubscriptionUserChoise',
        ),
    ]
