# Generated by Django 3.2.13 on 2023-02-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20230218_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='random_coffee_current_partner_id',
            new_name='random_coffee_last_partner_id',
        ),
    ]
