# Generated by Django 3.2.13 on 2023-02-18 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_rename_random_coffee_current_partner_id_user_random_coffee_last_partner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_is',
        ),
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_last_partner_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_past_partners',
        ),
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_tg_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_today',
        ),
        migrations.CreateModel(
            name='RandomCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_coffee_is', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Я хочу участвовать в клубном Random Coffee!')),
                ('random_coffee_tg_link', models.CharField(max_length=128, null=True, verbose_name='Ваш Телеграм для связи с собеседником')),
                ('random_coffee_today', models.BooleanField(default=True)),
                ('random_coffee_past_partners', models.TextField(null=True)),
                ('random_coffee_last_partner_id', models.UUIDField(default=uuid.uuid4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee', to='users.user')),
            ],
            options={
                'db_table': 'random_coffee',
            },
        ),
    ]
