# Generated by Django 3.2.13 on 2023-02-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20230218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcoffee',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee', to='users.user'),
        ),
    ]
