# Generated by Django 3.2.13 on 2023-02-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_randomcoffee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCoffeeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_from_first', models.JSONField(null=True)),
                ('feedback_from_second', models.JSONField(null=True)),
                ('first_user', models.ForeignKey(db_column='first_user', on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee_logs_first_user', to='users.user')),
                ('second_user', models.ForeignKey(db_column='second_user', on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee_logs_second_user', to='users.user')),
            ],
            options={
                'db_table': 'random_coffee_logs',
            },
        ),
    ]
