# Generated by Django 3.2.13 on 2023-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_randomcoffeelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcoffeelogs',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
