# Generated by Django 3.2.13 on 2023-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_randomcoffeelogs_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomCoffeeLogs',
        ),
    ]
