# Generated by Django 3.2.13 on 2023-02-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_delete_randomcoffeelogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCoffeeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.JSONField(null=True)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee_logs_user', to='users.user')),
                ('user_buddy', models.ForeignKey(db_column='user_buddy', on_delete=django.db.models.deletion.CASCADE, related_name='random_coffee_logs_user_buddy', to='users.user')),
            ],
            options={
                'db_table': 'random_coffee_logs',
            },
        ),
    ]
