# Generated by Django 3.2.13 on 2023-02-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20230227_0940'),
        ('users', '0047_randomcoffeelogs'),
    ]

    operations = [
    ]
