# Generated by Django 3.2.13 on 2023-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_merge_0040_auto_20230227_0940_0047_randomcoffeelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_email_digest',
            field=models.BooleanField(default=False, verbose_name='Ежедневная e-mail рассылка '),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_email_digest',
            field=models.BooleanField(default=False, verbose_name='Еженедельная e-mail рассылка '),
        ),
    ]
