# Generated by Django 3.2.13 on 2023-02-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20230227_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomcoffee',
            name='random_coffee_last_partner_id',
        ),
    ]
