# Generated by Django 3.2.13 on 2023-02-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_remove_randomcoffee_random_coffee_last_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcoffee',
            name='random_coffee_last_partner_id',
            field=models.UUIDField(null=True),
        ),
    ]
