# Generated by Django 3.2.13 on 2023-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20230228_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dima', max_length=128)),
                ('dima_count', models.IntegerField(null=True)),
            ],
        ),
    ]
