# Generated by Django 3.2.13 on 2023-03-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_delete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
