# Generated by Django 3.2.13 on 2023-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_delete_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcoffee',
            name='coffee_activation_time',
            field=models.DateTimeField(null=True, verbose_name='Время активации опции'),
        ),
        migrations.AddField(
            model_name='randomcoffee',
            name='coffee_deny',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='randomcoffee',
            name='coffee_done',
            field=models.IntegerField(default=0),
        ),
    ]
