# Generated by Django 3.2.13 on 2023-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20230321_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_helpfullness_digest',
            field=models.BooleanField(default=False, verbose_name='Ползеность дня'),
        ),
    ]
