# Generated by Django 3.2.13 on 2023-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_day_helpfullness_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcoffee',
            name='last_coffee_message_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='randomcoffee',
            name='random_coffee_is',
            field=models.BooleanField(default=False, verbose_name='Я хочу участвовать в клубном Random Coffee!'),
        ),
    ]
