# Generated by Django 3.2.13 on 2023-04-19 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20230330_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffilateVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=248, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'affiliate_visit',
            },
        ),
        migrations.CreateModel(
            name='AffiliateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('percent', models.PositiveSmallIntegerField(default=10)),
                ('fee_type', models.CharField(choices=[('MONEY', 'Деньги'), ('DAYS', 'Дни')], default='Дни', max_length=24)),
                ('sum', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'affiliate_info',
            },
        ),
        migrations.CreateModel(
            name='UserAffilate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.affiliateinfo')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_affilate', to='users.user')),
                ('unique_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.affilatevisit', to_field='code')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user')),
            ],
            options={
                'db_table': 'user_affiliate',
            },
        ),
    ]
