# Generated by Django 3.2.13 on 2023-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_affilatevisit_affiliateinfo_useraffilate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliateinfo',
            old_name='link',
            new_name='parametr',
        ),
        migrations.AddField(
            model_name='affiliateinfo',
            name='url',
            field=models.CharField(default='http://127.0.0.1:8000/post/2/', max_length=248),
        ),
        migrations.AlterField(
            model_name='affiliateinfo',
            name='fee_type',
            field=models.CharField(choices=[('MONEY', 'Деньги'), ('DAYS', 'Дни')], default='Дни', max_length=24, verbose_name='Как я хочу получать вознаграждение'),
        ),
    ]
