# Generated by Django 3.2.13 on 2023-04-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20230419_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraffilate',
            name='user_id',
        ),
        migrations.CreateModel(
            name='AffiliateLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_fee_type', models.CharField(choices=[('MONEY', 'Деньги'), ('DAYS', 'Дни')], max_length=24)),
                ('type_of_action', models.CharField(choices=[('PAY_BY_AFFILATE', 'paid for membership'), ('GET_BY_MONEY', 'get money from club')], max_length=48, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=248, null=True)),
                ('affilated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affilate_creator', to='users.user')),
            ],
            options={
                'db_table': 'affiliate_logs',
            },
        ),
    ]
