# Generated by Django 3.2.13 on 2023-04-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20230419_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelogs',
            name='affilated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user'),
        ),
    ]
