# Generated by Django 3.2.13 on 2023-04-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_affiliatelogs_affilated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelogs',
            name='affilate_status',
            field=models.CharField(choices=[('FIRST_TIME', 'come first time'), ('REGISTRATION_DONE', 'come to registration form')], default='come first time', max_length=48),
        ),
        migrations.AlterModelTable(
            name='affiliatelogs',
            table='affilate_logs',
        ),
    ]
