# Generated by Django 3.2.13 on 2023-04-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20230420_0656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateLogs',
            new_name='AffilateLogs',
        ),
    ]
