# Generated by Django 3.2.13 on 2023-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_affilatelogs_identify_new_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affilatelogs',
            old_name='created_at',
            new_name='time_firstly_come',
        ),
        migrations.AddField(
            model_name='affilatelogs',
            name='time_come_on_intro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='affilate_status',
            field=models.CharField(choices=[('FIRST_TIME', 'come first time'), ('REGISTRATION_DONE', 'come to intro form')], default='come first time', max_length=48),
        ),
    ]
