# Generated by Django 3.2.13 on 2023-04-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20230420_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilatelogs',
            name='affilated_user',
            field=models.ForeignKey(db_column='affilated_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user'),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='affilate_creator', to='users.user'),
        ),
        migrations.AlterField(
            model_name='affiliateinfo',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterField(
            model_name='useraffilate',
            name='affiliate_id',
            field=models.ForeignKey(db_column='affiliate_id', on_delete=django.db.models.deletion.CASCADE, to='users.affiliateinfo'),
        ),
        migrations.AlterField(
            model_name='useraffilate',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_affilate', to='users.user'),
        ),
        migrations.AlterField(
            model_name='useraffilate',
            name='unique_code',
            field=models.ForeignKey(db_column='unique_code', on_delete=django.db.models.deletion.CASCADE, to='users.affilatevisit', to_field='code'),
        ),
    ]
