# Generated by Django 3.2.13 on 2023-04-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20230420_1452'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffiliateInfo',
            new_name='AffilateInfo',
        ),
        migrations.RemoveField(
            model_name='useraffilate',
            name='affiliate_id',
        ),
        migrations.AddField(
            model_name='useraffilate',
            name='affilate_id',
            field=models.ForeignKey(db_column='affilate_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.affilateinfo'),
        ),
        migrations.AlterModelTable(
            name='affilateinfo',
            table='affilate_info',
        ),
        migrations.AlterModelTable(
            name='affilatevisit',
            table='affilate_visit',
        ),
        migrations.AlterModelTable(
            name='useraffilate',
            table='user_affilate',
        ),
    ]
