# Generated by Django 3.2.13 on 2023-04-24 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_affilatelogs_time_firstly_come'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='percent_log',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='identify_new_user',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='time_firstly_come',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
