# Generated by Django 3.2.13 on 2023-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20230424_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='admin_comment',
            field=models.TextField(null=True),
        ),
    ]
