# Generated by Django 3.2.13 on 2023-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_affilatelogs_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='money_withdraw',
            field=models.BooleanField(default=False),
        ),
    ]
