# Generated by Django 3.2.13 on 2023-04-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_affilatelogs_money_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilateinfo',
            name='sum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
