# Generated by Django 3.2.13 on 2023-04-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_alter_affilateinfo_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='admin_comment_time',
            field=models.DateTimeField(null=True),
        ),
    ]
