# Generated by Django 3.2.13 on 2023-04-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_affilatelogs_admin_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilatelogs',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affilate_creator', to='users.user'),
        ),
    ]
