# Generated by Django 3.2.13 on 2023-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_alter_affilatelogs_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilatelogs',
            name='type_of_action',
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='affilate_status',
            field=models.CharField(default='come first time', max_length=48),
        ),
    ]
