# Generated by Django 3.2.13 on 2023-04-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20230425_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilatelogs',
            name='creator_fee_type',
            field=models.CharField(choices=[('MONEY', 'Деньги'), ('DAYS', 'Дни')], max_length=24, null=True),
        ),
    ]
