# Generated by Django 3.2.13 on 2023-04-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_affilatelogs_creator_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilatelogs',
            name='admin_comment',
        ),
        migrations.RemoveField(
            model_name='affilatelogs',
            name='money_withdraw',
        ),
    ]
