# Generated by Django 3.2.13 on 2023-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20230425_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilatelogs',
            name='comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
