# Generated by Django 3.2.13 on 2023-04-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_alter_affilatelogs_percent_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilateinfo',
            name='fee_type',
            field=models.CharField(choices=[('DAYS', 'Дни'), ('MONEY', 'Деньги')], default='Дни', max_length=24, verbose_name='Как я хочу получать вознаграждение'),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='creator_fee_type',
            field=models.CharField(choices=[('DAYS', 'Дни'), ('MONEY', 'Деньги')], max_length=24, null=True),
        ),
    ]
