# Generated by Django 3.2.13 on 2023-04-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20230425_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='admin_comment',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
