# Generated by Django 3.2.13 on 2023-04-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_affilatelogs_admin_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affilatelogs',
            old_name='admin_comment_time',
            new_name='affilate_time_was_set',
        ),
        migrations.RemoveField(
            model_name='affilatelogs',
            name='time_come_on_intro',
        ),
    ]
