# Generated by Django 3.2.13 on 2023-05-02 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20230426_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affilatevisit',
            old_name='ref',
            new_name='ref_url',
        ),
        migrations.AlterField(
            model_name='affilatevisit',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
