# Generated by Django 3.2.13 on 2023-05-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20230502_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatevisit',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_affilate_creator', to='users.user'),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_affilate_creator', to='users.user'),
        ),
    ]
