# Generated by Django 3.2.13 on 2023-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20230502_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatevisit',
            name='affilate_status',
            field=models.CharField(default='come first time', max_length=48),
        ),
        migrations.AddField(
            model_name='affilatevisit',
            name='last_page_view_time',
            field=models.DateTimeField(null=True),
        ),
    ]
