# Generated by Django 3.2.13 on 2023-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20230502_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraffilate',
            old_name='unique_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='affilate_status',
            field=models.CharField(default='user visited site', max_length=48),
        ),
        migrations.AlterField(
            model_name='affilatevisit',
            name='affilate_status',
            field=models.CharField(default='user visited site', max_length=48),
        ),
    ]
