# Generated by Django 3.2.13 on 2023-05-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20230502_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraffilate',
            name='affilated_user',
            field=models.ForeignKey(db_column='affilated_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user'),
        ),
        migrations.AlterField(
            model_name='affilatelogs',
            name='affilated_user',
            field=models.ForeignKey(db_column='affilated_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_affilated_user', to='users.user'),
        ),
    ]
