# Generated by Django 3.2.13 on 2023-05-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_auto_20230502_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffilateRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('affilate_id', models.ForeignKey(db_column='affilate_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.affilateinfo')),
                ('affilated_user', models.ForeignKey(db_column='affilated_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affilated_user', to='users.user')),
                ('code', models.ForeignKey(db_column='unique_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.affilatevisit', to_field='code')),
                ('creator_id', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_affilate', to='users.user')),
            ],
            options={
                'db_table': 'affilate_relation',
            },
        ),
        migrations.RenameField(
            model_name='affilatelogs',
            old_name='identify_new_user',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='affilatelogs',
            name='affilate_status',
        ),
        migrations.RemoveField(
            model_name='affilatelogs',
            name='affilate_time_was_set',
        ),
        migrations.RemoveField(
            model_name='affilatelogs',
            name='time_firstly_come',
        ),
        migrations.AddField(
            model_name='affilatelogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserAffilate',
        ),
    ]
