# Generated by Django 3.2.13 on 2023-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_auto_20230502_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilatelogs',
            name='bonus_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
