# Generated by Django 3.2.13 on 2023-05-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_affilatelogs_bonus_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilaterelation',
            name='affilate_id',
        ),
        migrations.AddField(
            model_name='affilaterelation',
            name='fee_type',
            field=models.CharField(choices=[('DAYS', 'Дни'), ('MONEY', 'Деньги')], default='Дни', max_length=24),
        ),
        migrations.AddField(
            model_name='affilaterelation',
            name='percent',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
