# Generated by Django 3.2.13 on 2023-05-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_auto_20230508_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilatelogs',
            name='admin_comment',
        ),
    ]
