# Generated by Django 3.2.13 on 2023-05-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_remove_affilatelogs_admin_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilatevisit',
            name='affilate_status',
        ),
        migrations.RemoveField(
            model_name='affilatevisit',
            name='last_page_view_time',
        ),
    ]
