# Generated by Django 3.2.13 on 2023-05-22 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0092_auto_20230521_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilaterelation',
            name='code',
        ),
        migrations.AlterField(
            model_name='affilatevisit',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
