# Generated by Django 3.2.13 on 2023-05-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20230522_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilaterelation',
            name='last_product',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
