# Generated by Django 3.2.13 on 2023-05-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_affilaterelation_last_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilaterelation',
            name='last_product',
        ),
    ]
