# Generated by Django 3.2.13 on 2023-05-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_remove_affilaterelation_last_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilaterelation',
            name='last_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_for_affilate', to='users.subscriptionplan'),
        ),
    ]
