# Generated by Django 3.2.13 on 2023-05-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_affilaterelation_last_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilateinfo',
            name='url',
        ),
    ]
