# Generated by Django 3.2.13 on 2023-07-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_remove_affilateinfo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilaterelation',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='affilaterelation',
            name='percent',
        ),
    ]
