# Generated by Django 3.2.13 on 2023-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_auto_20230704_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcoffee',
            name='last_bot_activity',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='randomcoffee',
            name='last_datetime_bot_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
