# Generated by Django 3.2.13 on 2023-01-13 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0028_auto_20221128_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMesage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('time_delay', models.DateTimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('is_finish_of_queue', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMesageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('was_sended', models.DateTimeField()),
                ('is_series_finished', models.BooleanField(default=False)),
                ('last_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_message_id', to='telegramessage.telegrammesage')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_queue', to='users.user')),
            ],
        ),
    ]
