# Generated by Django 3.2.13 on 2023-01-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_finish_of_queue',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
