# Generated by Django 3.2.13 on 2023-01-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0003_alter_telegrammesage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammesage',
            name='time_delay',
        ),
        migrations.AddField(
            model_name='telegrammesage',
            name='days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Дни задержки'),
        ),
        migrations.AddField(
            model_name='telegrammesage',
            name='hours',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Часы задержки'),
        ),
        migrations.AddField(
            model_name='telegrammesage',
            name='minutes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Минуты задержки'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Заархивировать'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_finish_of_queue',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Сообщение является конечным в серии сообщений'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название сообщения'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterModelTable(
            name='telegrammesage',
            table='telegram_messages',
        ),
    ]
