# Generated by Django 3.2.13 on 2023-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0004_auto_20230119_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesage',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Дни задержки'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='hours',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Часы задержки'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='minutes',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Минуты задержки'),
        ),
    ]
