# Generated by Django 3.2.13 on 2023-01-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0005_auto_20230119_0836'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegrammesagequeue',
            table='telegram_messages_queue',
        ),
    ]
