# Generated by Django 3.2.13 on 2023-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0006_alter_telegrammesagequeue_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammesagequeue',
            name='was_sended',
        ),
        migrations.AddField(
            model_name='telegrammesagequeue',
            name='first_time_was_sended',
            field=models.DateTimeField(blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Заархивировать'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_finish_of_queue',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Сообщение является конечным в серии сообщений'),
        ),
    ]
