# Generated by Django 3.2.13 on 2023-01-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0007_auto_20230119_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesagequeue',
            name='first_time_was_sended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
