# Generated by Django 3.2.13 on 2023-01-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0008_alter_telegrammesagequeue_first_time_was_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesagequeue',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_id', to='telegramessage.telegrammesage'),
        ),
    ]
