# Generated by Django 3.2.13 on 2023-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0009_alter_telegrammesagequeue_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammesagequeue',
            name='last_time_message_sended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
