# Generated by Django 3.2.13 on 2023-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0010_telegrammesagequeue_last_time_message_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammesagequeue',
            name='id_of_sended_messages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
