# Generated by Django 3.2.13 on 2023-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0011_telegrammesagequeue_id_of_sended_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesage',
            name='days',
            field=models.PositiveIntegerField(default=0, verbose_name='Дни задержки'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='hours',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Часы задержки'),
        ),
        migrations.AlterField(
            model_name='telegrammesage',
            name='minutes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Минуты задержки'),
        ),
    ]
