# Generated by Django 3.2.13 on 2023-01-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0012_auto_20230122_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammesage',
            name='is_archived',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Сохранить как черновик'),
        ),
    ]
