# Generated by Django 3.2.13 on 2023-03-23 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0013_alter_telegrammesage_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayHelpfulness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название сообщения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('image_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на изображение')),
                ('order', models.IntegerField(null=True)),
                ('is_archived', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Сохранить как черновик')),
            ],
            options={
                'db_table': 'day_help_messages',
            },
        ),
    ]
