# Generated by Django 3.2.13 on 2023-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0014_dayhelpfulness'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhelpfulness',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
    ]
