# Generated by Django 3.2.13 on 2023-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0015_dayhelpfulness_is_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhelpfulness',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=256, verbose_name='Ссылка на изображение'),
        ),
    ]
