# Generated by Django 3.2.13 on 2023-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0016_alter_dayhelpfulness_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhelpfulness',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
