# Generated by Django 3.2.13 on 2023-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramessage', '0017_alter_dayhelpfulness_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayhelpfulness',
            options={'ordering': ['order'], 'verbose_name': 'Полезняха дня'},
        ),
        migrations.AlterField(
            model_name='dayhelpfulness',
            name='order',
            field=models.IntegerField(null=True, unique=True, verbose_name='Порядок отправки'),
        ),
    ]
