# Generated by Django 3.2.13 on 2023-06-27 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_remove_affilateinfo_url'),
        ('telegramessage', '0018_auto_20230330_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammesage',
            name='test_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_user', to='users.user'),
        ),
    ]
