# Generated by Django 3.2.13 on 2023-06-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_remove_affilateinfo_url'),
        ('telegramessage', '0019_telegrammesage_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhelpfulness',
            name='test_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_helpfulness', to='users.user'),
        ),
    ]
