# Generated by Django 3.2.13 on 2023-06-27 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0097_remove_affilateinfo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolIntro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название сообщения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('image_url', models.CharField(blank=True, default=None, max_length=256, verbose_name='Ссылка на изображение')),
                ('order', models.IntegerField(null=True, unique=True, verbose_name='Порядок отправки')),
                ('is_archived', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Сохранить как черновик')),
                ('is_sended', models.BooleanField(default=False)),
                ('test_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cool_intros_test_users', to='users.user')),
            ],
            options={
                'db_table': 'cool_intros',
            },
        ),
    ]
