# Generated by Django 3.2.13 on 2023-12-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolintro',
            name='telegram_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
