# Generated by Django 3.2.13 on 2023-07-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_auto_20230704_1241'),
        ('auth', '0007_session_original_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='original_user',
            field=models.ForeignKey(db_column='original_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to='users.user'),
        ),
    ]
