# Generated by Django 3.2.13 on 2022-11-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20211022_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['price_days', 'code']},
        ),
    ]
